### ISSUE TITLE
The music fix patch crashes the patcher

### ISSUE THREAD

**Issue by lowendgamer** [pyriell/gs2-bugfixes#13]
It always crashes the patcher every time when the music fix is selected. How to include it without crashing?

**Comment by pyriell** [comment]
It's most likely not crashing.  The patch just has to change a bunch of random bytes in every sector of the audio.  It takes ages, depending on your PC, and the dialog will stop responding.  If you keep clicking on it, Windows will assume it's crashed because it's not handling messages.  Just leave it alone, and it'll be fine.

**Comment by lowendgamer** [comment]
> It's most likely not crashing. The patch just has to change a bunch of random bytes in every sector of the audio. It takes ages, depending on your PC, and the dialog will stop responding. If you keep clicking on it, Windows will assume it's crashed because it's not handling messages. Just leave it alone, and it'll be fine.

Thank you! It worked.
