### ISSUE TITLE
GS1 Load - Tai Ho as non default.

### ISSUE THREAD

**Issue by woj1993** [pyriell/gs2-bugfixes#2]
Hi. First: thanks for patches.
Second from what I understand this patch is changing one character to another. I thing that game changing patches should be non default until they are fixes for bugs.

I also want to ask you to make Suikoden 1 patches available on Github.

**Comment by pyriell** [comment]
This one is a matter of some debate.  The "replaced" character is Vincent, who wasn't even playable in the first game.  He has stats in it, but they're just initialized values that can't be changed, so there's no value in him getting bonuses in Suikoden 2.  Whether he was included by mistake (bug) isn't something I can prove definitively, but it's the explanation that makes the most sense to me, and most of the other fans I've talked to agree.  Meanwhile, Tai Ho is playable in both games, and is mysteriously the only carried-over, playable character who is ineligible for import bonuses.

Having the patch on by default is just a judgment call.  My thinking is that most users would prefer to have the import potentially do something useful, rather than giving 0 bonuses to a character they had no control over in the first game.  While I usually tend toward preserving Konami's intent, in this case I let user preference make the decision, because Konami's intent seems unclear to me.

**Comment by woj1993** [comment]
@pyriell So it doesn't change character but only fixes bonuses transferred to second from first game?
If so description should mention this, because I was thinking that you cut out Vincent and added Tai Ho as character. Then this should be bug fix and description should be something like this:
"Suikoden 2 has probably bug in character import. It tries to give bonuses to new playable character "Vincent", but because he is unplayable in first game bonuses for him are equal to 0. Tai Ho is only playable character in both games that don't have this bonuses. This patch changes game so it propery applies bonuses to Tai Ho not to Vincent."

P.S. What about patches to Suikoden 1?

**Comment by pyriell** [comment]
In the readme file, it says:
	GS1 Load - Tai Ho
	Swaps Vincent, who was unplayable in Suikoden, for Tai Ho, with a default level of 27.  This gives him the same level bonus opportunities as Hix, Luc, and Tengaar, with a maximum level of 47 if he is 99 in your Suikoden save and wins the +5 bonus for highest level.  His weapon can be as high as level 10.  With the Rune Import patch, he will still not be able to transfer runes.  He never gets a second slot, and he starts with a Killer Rune affixed to his lone slot in Suikoden 2.

Space is sort of precious in the UI, so the descriptions there are much more terse.

The descriptions mean Vincent was removed from the GS1 Import, not the game.  I can probably rephrase a bit, but I don't think it's a critical issue.

I can start a new repo for the S1 patch.  To do the job properly I need to gather up some things I haven't looked for in a long time, though.

**Comment by woj1993** [comment]
@pyriell Can you upload for now "compiled" version of Suikoden 1 fixes? I would be grateful for at least zip with them or link because I can't find them anywhere to patch game. Even in this tread.

P.S. I saw description in patching menu for this patch and it seems mostly fine.

**Comment by pyriell** [comment]
http://herrvillain.net/suikoden/gs1/GS1_Patch_1.00.002_2013-11-27.zip

**Comment by woj1993** [comment]
Thanks.
