### ISSUE TITLE
Question: Two River Bug fixed yet?

### ISSUE THREAD

**Issue by CloudMcRip** [pyriell/gs2-bugfixes#3]
Hi Pyriell, thanks for supporting and hard working on the patch for Suikoden 2. A few years ago i asked if you can fix a bug that appears in every German version of Suikoden 2. It's the Two River Bug, where you fight against Highland Soldiers and on the last fight it crashed the game. 
I made a Video about it: 
https://youtu.be/Dxx5Ll2Zpzw

Was you able to fix it?
If you need anything, let me know.

**Comment by pyriell** [comment]
I think you Dropboxed me a save state ages ago, but I don't know if I still have it.  Do you still have it?

I'm pretty sure this is purely a translation issue.  They didn't realize they'd gone a little overboard on string lengths and in the process broke the game's ability to detect choice selections properly.  The whole thing may be fixable by changing "Es besteht immer noch{\n}eine Chance.{\n}Immer." to remove one of the newlines.  If that pushes the text beyond the box, it might also be changed to something shorter, like maybe, "Es gibt noch eine Chance.{\n}Immer."  However, I don't know if that wrecks the mayor's idiom or not, and it definitely destroys the repetition of "immer", which I think is why the original translation was used.

In any case, these strings occur in 6 different files, thanks to incessant file reuse, and I've no idea which one is actually in use during these events.

**Comment by pyriell** [comment]
I dug up my test run saves, found one fairly close to this chain of events, and edited it to load with the German version.  It's VH12.BIN that's being used, at least the way I ran it, and changing the last newline in the string to just a space fixes the issue.

I will probably alter the string in all files, just to be on the safe side.  I don't think there's an alternate set of events here, but one of the duplicates could still exist for an obscure reason other than copy/paste.

**Comment by pyriell** [comment]
OK, the latest set of revisions has a fix for this.  Let me know if anything is out of place due to the text changes.  I've tested that particular scenario twice, and haven't noticed anything out of kilter.

I also realized as I was playing through that it's the hero talking at that point.  I don't know why I thought it was Makai offering choices rather than just picking what the MC should say.  So I guess there was never a worry about ruining a characterization by changing the translation.  Luckily, it wasn't necessary anyway.  Although, as if to remind me how bad the translation is, I got Chain Letters twice from the Highland Soldiers.
