### ISSUE TITLE
Doesn't work in paths with braces

### ISSUE THREAD

**Issue by TzakShrike** [pyriell/gs2-bugfixes#8]
While its fine for the disc images to be located in paths with spaces, putting gs2-bugfixes in a path with a space causes it to fail immediately.

**Comment by pyriell** [comment]
Worked fine for me.  Did you get any logs out of it, or any other details you can provide?

**Comment by TzakShrike** [comment]
OK found time to test it a little more. It turns out its not so much spaces that it can't handle, but brackets (). It's fairly obvious how it fails if you have two sets of brackets in a single folder above the final folder. Can you try putting some of those in and test again?

**Comment by pyriell** [comment]
Ah, yeah.  That's a weakness of the Windows CMD shell.  It thinks the closing parenthesis of your file path is closing out the code block because it's stupid.

The two most common things that usually help don't want to work in this instance (one of them was already in place).  I'll see what I can do, but I may just put advice against such paths in the readme.

**Comment by TzakShrike** [comment]
I've resolved this issue. I'll PR soon (but I have to go out first, so maybe I'll do the actual PR tomorrow).
